from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(728, 567)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Input_item = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Input_item.sizePolicy().hasHeightForWidth())
        self.Input_item.setSizePolicy(sizePolicy)
        self.Input_item.setMinimumSize(QtCore.QSize(100, 20))
        self.Input_item.setObjectName("Input_item")
        self.verticalLayout_2.addWidget(self.Input_item)
        self.aucList = QtWidgets.QTableWidget(self.centralwidget)
        self.aucList.setObjectName("aucList")
        self.aucList.setColumnCount(0)
        self.aucList.setRowCount(0)
        self.verticalLayout_2.addWidget(self.aucList)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Graph_time = QtWidgets.QLabel(self.centralwidget)
        self.Graph_time.setMinimumSize(QtCore.QSize(400, 300))
        self.Graph_time.setObjectName("Graph_time")
        self.verticalLayout_3.addWidget(self.Graph_time)
        self.Info = QtWidgets.QLabel(self.centralwidget)
        self.Info.setMinimumSize(QtCore.QSize(200, 200))
        self.Info.setObjectName("Info")
        self.verticalLayout_3.addWidget(self.Info)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 728, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionReset_graph = QtWidgets.QAction(MainWindow)
        self.actionReset_graph.setObjectName("actionReset_graph")
        self.actionDelete_graph = QtWidgets.QAction(MainWindow)
        self.actionDelete_graph.setObjectName("actionDelete_graph")
        self.actionSaveData = QtWidgets.QAction(MainWindow)
        self.actionSaveData.setObjectName("actionSaveData")
        self.actionDelete_ALL_SavedData = QtWidgets.QAction(MainWindow)
        self.actionDelete_ALL_SavedData.setObjectName("actionDelete_ALL_SavedData")
        self.actionDeleteDataHistoryLot = QtWidgets.QAction(MainWindow)
        self.actionDeleteDataHistoryLot.setObjectName("actionDeleteDataHistoryLot")
        self.actionGetSavedLot = QtWidgets.QAction(MainWindow)
        self.actionGetSavedLot.setObjectName("actionGetSavedLot")
        self.menuHelp.addAction(self.actionReset_graph)
        self.menuHelp.addAction(self.actionDelete_graph)
        self.menuHelp.addAction(self.actionSaveData)
        self.menuHelp.addAction(self.actionDelete_ALL_SavedData)
        self.menuHelp.addAction(self.actionDeleteDataHistoryLot)
        self.menuHelp.addAction(self.actionGetSavedLot)
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Stalcraft Helper"))
        self.Graph_time.setText(_translate("MainWindow", "График цен"))
        self.Info.setText(_translate("MainWindow", "Информация о предмете"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionReset_graph.setText(_translate("MainWindow", "Reset graph"))
        self.actionDelete_graph.setText(_translate("MainWindow", "Delete graph"))
        self.actionSaveData.setText(_translate("MainWindow", "SaveData"))
        self.actionDelete_ALL_SavedData.setText(_translate("MainWindow", "Delete_ALL_SavedData"))
        self.actionDeleteDataHistoryLot.setText(_translate("MainWindow", "DeleteDataHistoryLot"))
        self.actionGetSavedLot.setText(_translate("MainWindow", "GetSavedLot"))
